version: '3'

services:
  # --------------------------------------------------
  # DATABASES
  # --------------------------------------------------
  mysql_database:
    container_name: 'backoffice'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    networks:

networks:
  # --------------------------------------------------
  # DOCKER NETWORK
  # --------------------------------------------------
  fix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
  # --------------------------------------------------
